### ISSUE TITLE
Hosts / services count

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#10]
Hosts count report 3 hosts UP and 21 DOWN whereas there is only 4 hosts ... 

![image](https://cloud.githubusercontent.com/assets/2932687/16797731/1d638c9c-48e9-11e6-897a-bcc1870f5540.png)

**Comment by mohierf** [comment]
As of now:
![image](https://cloud.githubusercontent.com/assets/2932687/16798122/d65139ce-48ea-11e6-844d-e9c3e1017617.png)

where as I have 4 hosts and 35 services.

**Comment by algorys** [comment]
Yes I found where is bug : 

https://github.com/Alignak-monitoring-contrib/alignak-app/blob/develop/alignak_app/application.py#L258-L262

Parameters are inverted :/
