### ISSUE TITLE
Include a console script in the setup.py installer

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#100]
It would be nice to run the app with an `alignak-app` script :wink:

**Comment by mohierf** [comment]
I do not know how it is with Windows but if you include a console_script in your setup.py, it will be available in the PATH and, as such, we will be able to run this script directly without its location folder. Easier, no?

**Comment by algorys** [comment]
If using `console_scripts`:

- On Linux:

Script will be in `~/.local/bin`, but will not be included in PATH. The current `alignak-app` script makes a `~/bin` directory and include in PATH if needed. See if it's useful or not.

- On Windows:

Installer makes a shortcut on desktop to start application. So I thing it's useless for this platform.

**Comment by algorys** [comment]
I think this can be closed ?
