### ISSUE TITLE
Default configuration file

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#111]
**1/** The default WS configuration is not complying with the settings.cfg file comment:  `web_service = no` whereas the comment says it defaults to yes.

You should:
```
;web_service = no
```

**2/** Use a default section for the alignak url will allow to use the `alignak_url` variable in the webui section.
```
[default]
alignak_url = http://demo.alignak.net

[Backend]
; Backend url
; ------------------------------------------------------------------------------------------
; The url of your Backend.
; Default is %(alignak_url)s:6000
alignak_backend = %(alignak_url)s:6000

; Web Service Url
; ------------------------------------------------------------------------------------------
; Url of your alignak Web Service. If "web_service" is set to "no", this settings has no effect.
; Default is %(alignak_url)s:8888
alignak_ws = %(alignak_url)s:8888

[Webui]
; Webui
; ------------------------------------------------------------------------------------------
; The url of your Webui
; Default is %(alignak_url)s
webui_url = %(alignak_url)s
```

**Comment by mohierf** [comment]
More simply, you may declare the `webui_url` variable in the Backend section of the file.

To be discussed, default ports:
- backend: 5000
- ws: 8888
- webui: 80 (no port)

@ddurieux any interest to have a port set to 6000 for the remote backend access ... I do not think it is of any interest!

**Comment by algorys** [comment]
Agree with this port. 

@mohierf  6000 is a mistake from my part to facilitate my tests. I can reset it by default to 5000.

**Comment by mohierf** [comment]
@algorys : 6000 is the current port used on the demo server. but @ddurieux will switch from 6000 to 5000

**Comment by algorys** [comment]
**1/** and **2/** are fixed.

Leave `webui` section, cause if WebUI is installed on another server, user should be capable to set its url.
