### ISSUE TITLE
Reload configuration when login fails

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#112]
Perharps it may be interesting to reload the configuration file when the login failed. This will allow to make another test after having modified the configuration without being obliged to exit and restart the app ...

**Comment by algorys** [comment]
Yes great idea. Iwas thinking about that during login window and add a menu in systray to reload configuration.

* Reload configuration in login form
* Add port to login server window
* Reload configuration menu in systray

**Comment by algorys** [comment]
All is implemented :metal:
