### ISSUE TITLE
Review notification system ?

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#113]
With the arrival of the banners, I wonder if we can not imagine another way of proceeding.

If we take the situation of a call-center (or monitoring team haha) that uses App. What will make the most sense?

1. Show, as of now, big notifications who resume states. Big notification is not accessible if it is closed. But we can "pin" it ! Banners just display "informative" messages.

2. Or we can send big notification at start and keep it accessible by menu (as a little dashboard in fact). And maybe merge this screen with alignak status ? Then use banners to send changes in states (ex: OK: +2 Hosts are UP, -2 Hosts are CRITICAL). Obviously, "mini-dashboard" is update also if user open it.

IMHO, I think 2 is better. User must just see if there is change and I think it's more friendly. More readable also, with help of colors. In addition user can consult the states all the time.

@ddurieux and @mohierf what do you think ?

**Comment by mohierf** [comment]
Nice idea for a next version

**Comment by algorys** [comment]
Banners can now send diff notifications

**Comment by algorys** [comment]
Notifier has no more PyQt import.

He just send `pyqtSignal` when it needed.

**Comment by algorys** [comment]
This feature is implemented. Now user can choose:

- To be warn by Dashboard popup or Banners or twice if there is changes
- Dashboard can be accessed continuously via the menus
- Daemon states are warn by Banners
- Actions are warned by Banners

**Comment by algorys** [comment]
Full implemented.
