### ISSUE TITLE
Spy a specific host

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#114]
The idea behind this issue is to let user "spy" a specific host. (I think @spea was interested in this idea)

By the way of configuration file or the UI, user choose an host (or maybe more ? or services ?). App then will check regularly this host. If something goes wrong, app send a tick (or other kind of notification... To be discussed) to prevent user.

If some team should monitor a specific kind of resources, servers or services, I think this feature (or something similar) should help ?

@ddurieux, @mohierf , your opinion ? If you have another view for something like that due to your XP ? 😄

**Comment by ddurieux** [comment]
It can be great for example for service type business rules ;)

So yes, it's a good idea

**Comment by mohierf** [comment]
Great idea! Let the user choose a to-be-spied host from the host synthesis view ... it will add an host to the spied hosts list and the user will get notified for this host.

**Comment by algorys** [comment]
Done :tada:
