### ISSUE TITLE
Add services acknowledge and downtime

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#117]
App currently propose only "acknowledge" and "downtime" only for host. We should add the same for services.

This requires the following:

- [x] separate each service into a QWidget
- [x] create an `action_manager` who manage _ack_ and _downtime_ 
- [x] send a `tick` when action is **True**
- [x] Include actions of Host in `action_manager`

**Comment by algorys** [comment]
Each service is now in a QWidget.

**Comment by algorys** [comment]
Action manager now check if href endpoint of post are `processed` or not.

**Comment by algorys** [comment]
Acknowledge and downtime services are implemented. 

Action Manager manage all actions.

Leave just ticks when actions are done :yum:

**Comment by mohierf** [comment]
Nice!

What do you mean with "Leave just tick"?

**Comment by algorys** [comment]
(Tick is a little popup who display messages; see #108)

1. When ack or downtime are processed, tick is send
2. When ack or downtime is done, tick is send

So the user is sure that his action has been taken into account

**Comment by mohierf** [comment]
Ok. I got it! It only remains appearing a tick :wink: 

IMHO, renaming `tick` as `banner` will be more clear for English language people. A tick is a very small part of time (*un moment*), or a sign in a form (*case à cocher*) or many other things ... but never an information or alert message sliding on the screen :disappointed:

**Comment by algorys** [comment]
All is working great :yum: 

:+1: for renaming

`Tick, TickManager -> Banner, BannerManager`

See 22e5de0. It is also more comprehensible in the code
