### ISSUE TITLE
Improve Acknowledge actions

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#118]
Currently, acknowledge action is done with default values, like comment.

When #117 is done, acknowledges should be configurable by user in UI. If we follow options found in Webui, the user must be able to:

- Sticky acknowledge: `sticky (bool)`
- Notifies or not: `notifies (bool)`
- Make ack persistent: `persistent (bool)`
- Set comment. (App still manage who send the acknowledge): `comment (str)`

when request an acknowledge.

**Comment by mohierf** [comment]
IMHO, allowing acknowledge on services is a higher priority than configuration :wink:

**Comment by algorys** [comment]
Yes it's in #117 :wink:

**Comment by algorys** [comment]
Implemented.
