### ISSUE TITLE
Improve Downtime action

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#119]
Currently, downtime action is done with default values, like time and comment.

When #117 is done, dowwtime should be configurable by user in a new Window. If we follow options found in Webui, the user must be able to:

- Fixed downtime: `fixed (bool)`
- Set duration of downtime: `duration (Integer)`
- Set downtime date range: `start_time (integer)` and `end_time (integer)` 

when request a downtime.

- See if it's possible to have a calendar or something like that to choose date range.

**Comment by mohierf** [comment]
Note that for a fixed downtime, only start and end time are necessary. You may use duration to compute the end time, but alignak will only consider start and end time.

 For not fixed downtime, only the start time and duration are necessary. Alignak will schedule a downtime for the choosen duration between the start and end time.

**Comment by algorys** [comment]
Implemented
