### ISSUE TITLE
Some ideas ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#12]
... to improve the app:
- [x] when linking to WebUI, link to a table
- [x] use an URL with filtering parameters (eg. search=)
  
  As an example: `http://127.0.0.1:5001/livestate_table?search=type:service%20state:WARNING` displays the livestate table filtered for services that are in a WARNING state

**Comment by mohierf** [comment]
**Note**: I am currently improving this feature in the Web UI and I will provide a doc for the available parameters...

**Comment by algorys** [comment]
:+1:

**Comment by algorys** [comment]
**Note:** I will fait, added ideas and think about how to integrate this

**Comment by mohierf** [comment]
I do not understand your last comment :open_mouth:

**Comment by algorys** [comment]
:yum: just said I will wait you finish improving this feature and implement after

**Comment by mohierf** [comment]
This feature is implemented... there is more information in the documentation for table filtering
