### ISSUE TITLE
Log under "{app}" instead of "C:\Users\..\Python\alignak-app" on Windows

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#121]
Currently, app log under  `C:\Users\user\AppData\Roaming\Python\alignak-app` when App is running under Windows. This is not very friendly...

App maybe should log under `C:\Program Files\Alignak-app` instead, so that the user can access it more easily. And like that, the log file will be right next to the configuration file.

Or maybe another directory... to be discussed.

**Comment by mohierf** [comment]
Perharps add a configuration variable to choose where log file is to be placed ?

**Comment by mohierf** [comment]
Use a configuration section as the WebUI does for the log file ? 

See https://github.com/Alignak-monitoring-contrib/alignak-webui/blob/develop/etc/settings.cfg#L149

**Comment by algorys** [comment]
Yes good idea to propose another folder. Because, if I want to log under Program Files, Windows ask Admin rights :disappointed:

**Comment by algorys** [comment]
Now user can choose directory and log file.
