### ISSUE TITLE
Create a contact view

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#122]
With the same concept as hte host view, we should have a contact view that will allow to:
- view the user main information
- allow to downtime the user
- view the host / service notification commands and periods
- display an information if the contact is in a valid notification period

**Comment by algorys** [comment]
Does this view should only display current user (the one use App) or propose a list of all users like host view ?

Does backend manage access to certain user or not (like hosts and services) ?

**Comment by mohierf** [comment]
In my idea, this view only displays the current logged-in user information. This will allow to know (as an example...) how the notifications are configured for this user

**Comment by algorys** [comment]
First version of user view.

Missing:

- [x] display icon for enable data (red cross or green checked)
- [x] make change password possible
- [x] make enable notifications possible

@mohierf for this last features, I've just to POST on backend with the new value ? Does I've to use special `endpoint` ?

**Comment by mohierf** [comment]
To change data in the backend you need to PATCH and not to POST on the `user` endpoint

**Comment by algorys** [comment]
Miss also:

- [x] Display name of user Realm
- [x] Make notes editable

**Comment by algorys** [comment]
User view is now finished. :tada:
