### ISSUE TITLE
Sort services in host synthesis view

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#123]
Services in host view should be sorted by criticity:
- CRITICAL,
- WARNING, 
- DOWNTIME,
- ACK,
- OK

You can use the `_state_id` to sort when getting from the backend :wink:

**Comment by algorys** [comment]
Hmm... what's the diff with #96 ? :wink: 

It seems that in Webui, you sort by `name`. Maybe it's better because:

- If host has many services, search will be easier
- User should find quickly the service he wants

But I think add service `aggregation` should be a good thing (like in #96) and more readable.

**Comment by mohierf** [comment]
#96 is better but, as default, is no aggregation exists, sorting with descending `state_id` will be the better display. Futhermore, when refreshing, the services list scroll position is lost ... so seeing at first the problems is a better view.

**Comment by algorys** [comment]
> Futhermore, when refreshing, the services list scroll position is lost ... so seeing at first the problems is a better view.

It's fixed on `develop`.

> as default, is no aggregation exists, sorting with descending state_id will be the better display

Ok, I'll do like that.

**Comment by algorys** [comment]
I currently display descending name in Host Synthesis view. Then with filters, you can choose what to display or not. It's faster and easy :smile: 

View also keep your choices when refresh or searching a new host.

e.g. If you have deselected `Disks` aggregation and you have this aggregation on next host, filter remains deselect.
