### ISSUE TITLE
Missing icon on Windows installation

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#124]
Adter a fresh Windows installation, the desktop shortcut is missing the alignak icon

![image](https://cloud.githubusercontent.com/assets/2932687/22054434/df670822-dd55-11e6-8f10-384de5b8bd5c.png)

An error is raised when trying to change the icon:
![image](https://cloud.githubusercontent.com/assets/2932687/22054491/20ee1290-dd56-11e6-9f18-851a7d54f90c.png)

Icon is back when selecting the alignak-app.exe as an icon source:
![image](https://cloud.githubusercontent.com/assets/2932687/22054543/66a3778a-dd56-11e6-8905-af8b01b03995.png)

**Comment by algorys** [comment]
@mohierf icon is here on Windows 10... on which Windows do you have this problem ?

What setup do you use ?

**Comment by algorys** [comment]
Ok I found problem. Icon is deleted after install... I'll release a new Setup to fix it :smiley:

**Comment by algorys** [comment]
Fix by 0dd5c18.
