### ISSUE TITLE
Host synthesis view, first opening

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#126]
On first opening of the host synthesis view, some nasty controls on the window:

![image](https://cloud.githubusercontent.com/assets/2932687/22141874/51e2c946-def4-11e6-8829-7173a716514e.png)

See in the services list ;)

**Comment by algorys** [comment]
Yes.

Text are corrected and icon is removed. 

`Services not available .... Search for a host before.` is display instead.
