### ISSUE TITLE
No icon created on the desktop

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#131]
With the new Win setup, I do not have any icon on my desktop

**Comment by algorys** [comment]
Last setup put icon for me... I do a new Windows Setup (40f9b7b) who create icon too.

Please, also be sure you have not uncheck "create shortcut" box during setup.

**Comment by algorys** [comment]
Ok for you @mohierf ?

**Comment by mohierf** [comment]
Ok
