### ISSUE TITLE
On host synthesis, when refreshing the application stopped

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#132]
As explained in the title, I had this problem once ... when alignak-app run from the installer ...

This issue is a simple notice of a problem. Do not care especially with it ... I will inform if it happens again

**Comment by mohierf** [comment]
I noticed several application stops ... when acknowledging a service.

**Comment by algorys** [comment]
Normally problem is solved on last Windows setup (see 40f9b7b). Can you confirm @mohierf ?

**Comment by algorys** [comment]
Ok for you @mohierf ?

**Comment by mohierf** [comment]
Yes it looks ok
