### ISSUE TITLE
Search host, not only use the beginning of the name

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#133]
The search field of the host synthesis do not care about characters in the middle of the name. 

Searching for `host-0015` ... if you enter `001` the sarch field do not propose anything whereas `host` proposes a list

**Comment by algorys** [comment]
Currently, I've found way to `CaseInsensitive` or propose all  `UnfilteredPopupCompletion`. Last one propose in fact all hosts and try to select the best match. But this seems not very useful.

**Comment by algorys** [comment]
Done for PyQt5 ca8da71.

Miss for PyQt4.

**Comment by algorys** [comment]
Due to #185, the PyQt4 support is abandoned. (see d1c6b6b)
