### ISSUE TITLE
System load ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#136]
I fell that the last version is loading the system more than the former one. Perhraps a simple feeling ... but I am feeling the application is less reactive than before ?

**Comment by algorys** [comment]
Yes I have notice that also. 

Especially when the host synthesis view is open. Maybe because the request are currently not very optimized.

The last version is not also optimized.

I'll try to improve that.

**Comment by algorys** [comment]
This problem was normally solved by #142. App return to Lite loading :wink:
