### ISSUE TITLE
Make Menu Icons more pretty

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#14]
Icons in menu are very crushed. 

They must be more net.

**Comment by algorys** [comment]
Now menu follow theme of Webui.

**Comment by mohierf** [comment]
If you want to use the same icons as the webui: 
- font awesome icons are available in SVG format here: http://www.flaticon.com/packs/font-awesome
- the CSS colors are defined in the Web UI : https://github.com/Alignak-monitoring-contrib/alignak-webui/blob/develop/alignak_webui/htdocs/css/alignak_webui-items.css
