### ISSUE TITLE
Application messages

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#140]
It may be interesting to "export" a list of all the application user messages: 

- [x] allow easy translation

- [x] allow user customization

**Comment by algorys** [comment]
For translation, I think it'll be my next work :) see #93 

When you say "messages" you talk about banner messages ? 

Otherwise :+1: for customization :wink:

**Comment by mohierf** [comment]
Banner and GUI messages ...

**Comment by algorys** [comment]
@mohierf all string are now available in folder [locale](/Alignak-monitoring-contrib/alignak-app/tree/develop/alignak_app/locales).

I think we can close this issue and open new if messages are not suitable ?
