### ISSUE TITLE
Repository fixes

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#141]
The current repository contains some files that, IMHO, should  not be git controlled:

- [ ] alignakapp/__pycache__ directory

- [ ] alignak_app.egg-info directory

- [ ] build directory

- [ ] dist directory

Create a *.gitignore* to exclude those files. **pycharme** makes it easy :wink:

**Comment by algorys** [comment]
I do not understand, these files are not in the repository ?!

In addition, there is already a [.gitignore](https://github.com/Alignak-monitoring-contrib/alignak-app/blob/develop/.gitignore) file :upside_down_face:

**Comment by mohierf** [comment]
Ok. I removed all the project and cloned again. Those files are no more present ... probably an older version
