### ISSUE TITLE
Rework Host Synthesis View

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#142]
Due to #132 and #136, Host Synthesis View seems to stuck during refresh.

It appears that refreshing `QWidget Objects` inside `QScrollView`  takes a lot of memory and blocks the user interface.

This QWidget must be rework.

**Comment by mohierf** [comment]
I do confirm ... as #132 I had many application stops when refreshing or when chosing another host in the view.

**Comment by algorys** [comment]
After having discussed on #pyqt irc, it appears that the scroll is not made to refresh big QWidgets like that.

I was advised to use QStackedWidget to stack QWidgets.

**Comment by algorys** [comment]
Rework finished.
