### ISSUE TITLE
Host synthesis view - sorting and filtering

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#143]
I may be very interesting to allow sorting and filtering the services in the view.

Sorting as #123 (criticity) or sorting on last check result.

Filtering on state to display only WARNING or CRITICAL or ...

**Comment by algorys** [comment]
As sayed in #96 and #123, I make **filters** for `states` and `aggregations`.

`Last check result` will be interesting also. I'll look at that.

**Comment by algorys** [comment]
See also #208.

**Comment by algorys** [comment]
App now sorted services by:

1: aggregation
2: acknowledge or downtime
3: state

Like that DOWN and CRITICAL items are display as first in aggregation view.
