### ISSUE TITLE
Without restart backend a new host can only found it by whole name

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#146]

**Comment by algorys** [comment]
App does request for new hosts, but does not update its host list.

**Comment by algorys** [comment]
With implementation of #99, I can now try to update list when backend is restart.

**Comment by algorys** [comment]
Now that app reconnect herself, she found new host in real time.

**Comment by algorys** [comment]
This issue is not solved. When import in backend, hosts are not proposed to user inside App without restart App.

**Comment by algorys** [comment]
Fixed. Now synthesis update its model regularly.
