### ISSUE TITLE
app-client dashboard-metrics

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#147]
**send metrics data via backend:**

- Measured backend answer by notification
- App-CPU consumption
- App-MEM consumption
- detected changes

**Comment by mohierf** [comment]
IMHO this feature is not that easy to implement ... we would rather suggest to the app administrator to use NSclient agent to monitor the `alignak-app` process activity. 

Proposing and NSClient `check_process` command configuration for this feature is the best solution @spea1 ?

**Comment by spea1** [comment]
The backend response times and detected changes can only evaluate the app.
So it would be possible to determine how the app behaves, to example from home via vpn.

**Comment by algorys** [comment]
@spea1, @mohierf do you think App could send metrics to backend ? Maybe by POST on backend ?

But IMHO this will slow down app execution on small devices... so want to keep this idea ?

**Comment by mohierf** [comment]
IMHO this feature is not essential and would not be that easy to implement ... for only small benefits.

**Comment by algorys** [comment]
Ok, that's what I think too. So I close it.
