### ISSUE TITLE
Improve backend requests

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#150]
Currently, App make many requests to backend who are not maybe necessary.

We should try to optimize that and make request only when needed to alleviate application.

**Comment by algorys** [comment]
Request only if Synthesis is visible and only if user type text : 3be2f1b

**Comment by algorys** [comment]
To increase performance, app now have a `DataManager` to manage backend requests and give data to App.

The goal here is to avoid small queries scattered all over the place.

**Comment by mohierf** [comment]
**"To increase requests"** ... sure about this? I would have written: **To increase performance** or **to decrease count of requests** ... 😉

**Comment by algorys** [comment]
@mohierf I corrected :wink:

**Comment by algorys** [comment]
- [x] Services actions are bugged.
- [x] Actions buttons should stay grey when refresh

**Comment by algorys** [comment]
It seems there is no performance gain with `data_manager` :cry:  previous version use about 30mo and new 40mo under Windows.

I think it's due to an additionnal process to update data...

For Linux it looks like it remains unchanged.

So maybe back to previous way to access to backend and simply limit request when it's really needed. It's look better. In addition, with the `data_manager` we have a waiting time when updating the data, so that's a bad point also.

**Comment by mohierf** [comment]
Going back to the previous behavior seems interesting to keep the app as simple as possible 😉

**Comment by algorys** [comment]
@ddurieux I think you can help :wink:

**Comment by algorys** [comment]
Thanks @ddurieux :wink:
