### ISSUE TITLE
Configure no notifications

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#155]
With the parameter `check_interval = 0`, the app should not raise any notification popup. Perharps it should not event get data from the backend ... this to avoir unuseful network traffic

Indeed, what is the current behavior when this parameter is set as `0` ?

**Comment by algorys** [comment]
> With the parameter check_interval = 0, the app should not raise any notification popup. 

:+1: 

> Indeed, what is the current behavior when this parameter is set as 0 ?

It appears that app check backend livesynthesis avery 0.00000? secondes :cry:

**Comment by algorys** [comment]
I've made a fix to not raise any notification if `check_interval = 0`.

> Perharps it should not event get data from the backend ... this to avoir unuseful network traffic

This is only `GET` to `livesynthesis` so I don't think it's a big traffic. Currently I use the same request to update menus in systray. This will be improved with #113 in future. So I just deactivate notification if set to **0**.

**Comment by algorys** [comment]
Implemented.
