### ISSUE TITLE
Host synthesis window height

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#158]
Host synthesis window height is not sized correctly:
![image](https://cloud.githubusercontent.com/assets/2932687/22782881/72cabe22-eec9-11e6-9d8c-07bd278d2973.png)

**Comment by algorys** [comment]
Under Linux or Windows ? I can't reproduce the problem.

Does it do it for all hosts or only those who have a lot of services ?

**Comment by algorys** [comment]
I confirm the bug. I'll fix that :wink:

**Comment by mohierf** [comment]
Perharps I have a special configuration ... two monitors with different heights ?

**Comment by algorys** [comment]
No. It seems it's sizing problem of QWidget inside window.

**Comment by algorys** [comment]
Fixed.
