### ISSUE TITLE
Problems view

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#162]
On the same model as the host synthesis view, the App should have a problems view. This view will display the current problems sorted by `business_impact` and then `state_id` to allow the user to acknowledge them or schedule downtimes. 
Something like: 
![image](https://cloud.githubusercontent.com/assets/2932687/22887135/2e793ce0-f201-11e6-9b4d-f2a58b6b80ba.png)

**Comment by algorys** [comment]
@mohierf I think now that the application has a drag and drop system, the problem view could use it.

When view is opened, user should be able to drag one problem to Host Synthesis view and display it.

Or just have buttons to display host in view.

**EDIT:** it seems that problems view need many informations. So drag and drop widgets will not be practical to display this data. I'll change to another model view.

**Comment by algorys** [comment]
The problem view is now complete.
