### ISSUE TITLE
History view

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#163]
Create an history view that will display the history for an host

**Comment by algorys** [comment]
@mohierf I've search on alignak doc and I can't find an endpoint to get this. 

Can you please tell me how get this kind of information ?

**Comment by mohierf** [comment]
Sure. The `history` endpoint of the Alignak backend stores many information about what happened: checks, alerts, notifications, ... 

 The backend stores the actions (recheck, ack, ...) but if you activated the `logs` module with the backend, all the monitoring events will also get stored in the history.

See: https://github.com/Alignak-monitoring-contrib/alignak-backend/blob/develop/alignak_backend/models/history.py

**Comment by algorys** [comment]
First version of history for host.

- [x] Miss type of history (check, ack, down)? This will help to define icon after.
- [x] CSS for QWidget
- [x] Add a refresh button

**Comment by algorys** [comment]
History is done :tada:
