### ISSUE TITLE
Aggregation / states filtering mismatch

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#165]
In the host synthesis view, when changing the aggregation filtering, the states filters are not considered. 

As an example, I excluded the OK state services and an aggregation. 
![image](https://cloud.githubusercontent.com/assets/2932687/22928678/f9100338-f2b7-11e6-97e5-2d5e0c9663dd.png)

When I reactivate the excluded aggregation, all the services, even if OK, are displayed in the list:
![image](https://cloud.githubusercontent.com/assets/2932687/22928669/e9ec7418-f2b7-11e6-82e5-8f91302a1378.png)

**Comment by algorys** [comment]
Fix by f99474f
