### ISSUE TITLE
State and colors ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#173]
I changed the color code in the WebUI to give a try with something more consistent...

What do you think about it?
![image](https://cloud.githubusercontent.com/assets/2932687/23199363/381ab91c-f8ce-11e6-8f54-5b46e38929f0.png)

![image](https://cloud.githubusercontent.com/assets/2932687/23199431/9d730bfc-f8ce-11e6-973d-ec4641314910.png)

And I will use light-grey and medium grey for acknowledge and downtims

**Comment by algorys** [comment]
I do not see the difference... 

UNREACHABLE will be in purple, and ack and downtime icon are in grey ?

**Comment by mohierf** [comment]
Yes that's it. On state icons when ack or downtime is set, the icon do not change its color but it is faded as Load and NetworkUsage on the second image.

And when Ack and downtime are used for a count (eg. top banner), I am using light and medium grey

**Comment by algorys** [comment]
For me grey is more for an empty count... maybe make ack and downtime yellow ?

**Comment by mohierf** [comment]
Why not? Let's give a try...

**Comment by algorys** [comment]
App now follow WebUI colors. Yellow seems a good idea.
