### ISSUE TITLE
Fix business impact stars

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#174]
As @mohierf say:

For business impact: 5=3 stars, 4=2 stars, 3=1 star, < 3 = no star at all

**Comment by mohierf** [comment]
See https://github.com/Alignak-monitoring-contrib/alignak-webui/blob/develop/alignak_webui/utils/helper.py#L203, using `less=2` will make the job 😉

**Comment by algorys** [comment]
See :  https://github.com/Alignak-monitoring-contrib/alignak-webui/issues/72

**Comment by algorys** [comment]
Done.
