### ISSUE TITLE
Logged-in with guest user

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#178]
When logged-in with a guest user account, the acknowledge and downtme commands should not be available. The `can_submit_commands` property of the user indicates whether he is allowed to send commands or not.

---
**Note** that the alignak backend should not accept the commands from a not authorized user 😖

**Comment by algorys** [comment]
Ok I'll disable button if `can_submit_commands` is False :sunglasses:

**Comment by algorys** [comment]
@mohierf does we have a user on demo server with `can_submit_commands` set to false ? 

If not where I can set this setting in my config files ?

**Comment by mohierf** [comment]
Sure. The `guest` user ...

**Comment by algorys** [comment]
Done.
