### ISSUE TITLE
Rework Dashboard View

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#179]
We can imagine a Dashboard more close as WebUI:

[![dashboard.png](https://s27.postimg.org/wg0e6gbyb/dashboard.png)](https://postimg.org/image/hk1uyv0jj/)

It's just an exemple, but I think vertical progressbar is more sexy.

**Comment by ddurieux** [comment]
not bad ;)

**Comment by spea1** [comment]
it is nice ;)

You like the challenge :DDD
Waterfall-diagrams https://www.think-cell.com

![waterfall-diagrams](https://cloud.githubusercontent.com/assets/20840532/23416568/a493e036-fde3-11e6-8b73-88f625ccc052.jpg)

**Comment by mohierf** [comment]
@algorys: @spea1 I cannot see the diagrams: 503 connection timeout 😞 

You know that you can copy / paste in github issue comments, it is better to keep the graphics...

**Comment by mohierf** [comment]
Nice, but I am not sure at all that histograms is the best visual representation for the overall system state ... histogram is not intended to display parts of a whole thing. Pies or doughnuts are more appropriate for this kind of statistics. See the Web UI dashboard widgets...

If your dashboard window layout is HTML / JS capable, it may be really easy to reuse the WebUI widgets to build this view 😉

**Comment by algorys** [comment]
I found a gist that do that: https://gist.github.com/anonymous/9ddca0de242a1c351c122dc7286f344f

**Comment by mohierf** [comment]
My idea was exactly the contrary of this 😉  Do not load a page from the webui, but rather use html/css/js inside your window ... I would provide the source code to build :)

**Comment by algorys** [comment]
After reviewing this issue, I think something like that would be more appropriate:

![app_dashboard](https://user-images.githubusercontent.com/8926922/30486179-f9397090-9a2f-11e7-8486-e1cba6e88859.png)

Logos for hosts and services link for their respective tables on WebUI, and buttons will do the same but with their filters.

**Comment by algorys** [comment]
See #208 now.
