### ISSUE TITLE
Remove Setup... exe from the git repo

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#180]
You should remove the Setup.exe file from the repo...

**Comment by algorys** [comment]
Yes I think too, it's taking too much place... but it was convenient for BETA testing...

**Comment by algorys** [comment]
Removed.

**Comment by mohierf** [comment]
Update the doc according to this removal ... explain tat the setup.exe will be in the release part of your github repository 😉

**Comment by algorys** [comment]
Done. Explain also you have to build your own setup for develop branch.
