### ISSUE TITLE
Login window not centered on screen

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#181]
The login window is not centered on the screen:
![image](https://cloud.githubusercontent.com/assets/2932687/23451926/62153906-fe62-11e6-87ea-838726b23321.png)

It seems that it is the bottom / right corner point of the window that is centered ...

**Comment by mohierf** [comment]
Perharps a useful information?
![image](https://cloud.githubusercontent.com/assets/2932687/23453293/1b2717ca-fe68-11e6-85eb-6c4169f929a8.png)

**Comment by algorys** [comment]
I reproduced the problem. Thanks for screens.

**Comment by algorys** [comment]
Fixed by 8c0c618
