### ISSUE TITLE
Keep PyQt4 compatiblity

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#185]
See if it's necessary for App to maintain PyQt4 support ?

For the following reasons:

- App will maybe be used mainly by Windows user. So Python3 and PyQt5 are used for this version.
- PyQt5 seems more complete than PyQt4
- More job to maintain
- Python3 is almost on all recent Linux

Conversely:

- We lose support of python2 :cry:  
- PyQt5 can be installed for python2 but requires self compiled from user (https://plashless.wordpress.com/2014/03/26/building-pyqt5-for-python2-7-on-a-clean-ubuntu-13-10-build-machine/ for example, not tested)

**Comment by mohierf** [comment]
+1 to keep only Python 3

**Comment by algorys** [comment]
Ok @ddurieux seems ok also. 

I'll remove in a next version.

If we follow https://github.com/Alignak-monitoring/alignak/issues/601 how I consider this change ?

**Comment by mohierf** [comment]
I will increment only the 'fixes' digit ...

**Comment by algorys** [comment]
PyQt4 support has been completely removed for `v0.6.4`
