### ISSUE TITLE
Windows installer - target directories

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#186]
Currently the Windows installer installs the application executables in `c:\program files\alignak-app` and the application extra files in the current user roaming data directory.  Moreover the application need to have write permission on both directories (eg. for settings.cfg and log files)

 This is a problem when the application is deployed with some automating tools like SCCM ... several problems:
 - setting rights in several directories that are not always write enabled
 - forbidding server user's profiles management

All the application fils shoud be located in the same and unique `c:`\program files`\alignak-app` directory. this will make it really easier to deploy and setup.

**Comment by algorys** [comment]
Normally App now put all files in `Program Files` directory.

The log stil available under `ProgramData\Alignak-app` folder.

**Comment by algorys** [comment]
I've updated documentation for this modification. 

We keep also compatibility with `pip` install on Windows (see #189 for more details).
