### ISSUE TITLE
Synthesis view, some remarks

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#190]
![image](https://cloud.githubusercontent.com/assets/2932687/23518919/56416956-ff75-11e6-8f96-561c69637e8e.png)

According to this view:

- [x] remove the message "Host services status" (not really useful)
- [x] make the host output wider. Perharps removing the left and right margins for the host information ?
- [x] host ack and downtimed icons should be placed like on the service area
- [x] remove the alias information for the host, it is still present under the host state icon
- [x] host information may only contain: name, address and importance
- [x] parents, is it of any interest ? not sure ...

- [x] services list item should not have the aggregation part, it is not really useful
- [x] services list item should have the service alias (eg. Paiement par CB (Svc_tagreading_c)
- [x] service information may not display Impact, description and fix actions if they are empty ...

**Comment by algorys** [comment]
@mohierf I've make a new version with your remarks :wink: . That was not easy for filtering, but I make it.

Here is a view (no ack, downtime and no customs actions:

![image](https://cloud.githubusercontent.com/assets/8926922/23591733/6ba32e88-01f5-11e7-9345-b677d6ae1454.png)

An another with ack and actions:

![image](https://cloud.githubusercontent.com/assets/8926922/23591744/a55dbaee-01f5-11e7-9854-e55ccc80ef38.png)

What do you think ?

- [x] restore grey for output ?

Like that, layouts stay as same for all.

**Comment by algorys** [comment]
- [x] Remove grey ack / downtime text for services. Icon still show if service is acknowledged or downtimed.
- [x] The host should also use this icons to prevent user.

**Comment by algorys** [comment]
Here is the last preview:

![image](https://cloud.githubusercontent.com/assets/8926922/23608680/cf994a24-026a-11e7-9826-f360754e3fc1.png)

Synthesis view is clearer like this.
