### ISSUE TITLE
Desktop icon for 0.6.3 is labelled with 0.6.2

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#194]
The icon created on the Windows desktop with the 0.6.3 installer is labelled as "Alignak App 0.6.2"

Perharps a simple "Alignak App" label would be enough ?

**Comment by algorys** [comment]
@mohierf Alignak-app should be enough, you're right. The habit of working where I have multiple versions of installed.

**Comment by algorys** [comment]
This is fixed in v0.6.4.
