### ISSUE TITLE
App setup on Windows 10

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#203]
When trying to install the app on Windows 10, I got this:
![image](https://user-images.githubusercontent.com/2932687/30534236-9c7f8e04-9c5d-11e7-9228-a15a188b8c44.png)

You must click on "Informations complémentaires" and then:
![image](https://user-images.githubusercontent.com/2932687/30534336-1966d350-9c5e-11e7-87e2-7f8ac6f1afac.png)

**Remark** perharps it may be explained in the documentation?

Once installation is finished: 
![image](https://user-images.githubusercontent.com/2932687/30534472-ac07089c-9c5e-11e7-9b08-825a039e9280.png)

**Remark**: voir app_workdir.ini ?

When clicking, the application starts but no file is opened :wink:

**Comment by algorys** [comment]
**1/** Ok I'll explain in documentation that application is not signed.

**2/** Normally, it should open notepad of Windows. Are you the administrator of your computer ? Can you please check rights in `C:\Program Files\Alignak-app` folder please ?

**Comment by mohierf** [comment]
For **2/** I am administrator but perharps I made a bad click ... I will confirm (or not...)  on a next installation 😉

**Comment by algorys** [comment]
@mohierf can you check with last version please ?

**Comment by mohierf** [comment]
Ok with last version

**Comment by algorys** [comment]
Ok @mohierf. Thanks.
