### ISSUE TITLE
Catch a better way the connection to backend

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#21]
Cuurently, if connection to backend fails, application exit without any message. There is just a trace in log file.

User should be informed that connection is wrong.

**Comment by mohierf** [comment]
You should even:
- keep a visual indicator for the connection status
- try periodically to restablish the connection

**Comment by algorys** [comment]
Yes great idea. I open corresponding issues:
- keep a visual indicator for the connection status #22 
- try periodically to restablish the connection #23
