### ISSUE TITLE
App start Color diff output (To info)

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#216]
This is not a mistake only for information ;)
![app-start-windows-and-ubuntu](https://user-images.githubusercontent.com/20840532/32144210-a6cf2630-bcb5-11e7-810a-1fbf184488f6.jpg)

**Comment by algorys** [comment]
Yes, I think it's due to systems who don't manage transparency of `png` in same way. So maybe I've to investigate on this.

But it have a style :wink:

**Comment by algorys** [comment]
Maybe this progress bar can be replaced by what the datamanager is collecting.

Like this, when you start App on a backend with a lot of hosts and services, the user will be informed of what is happening.

**Comment by algorys** [comment]
Done.
