### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#218]
![app-other icon](https://user-images.githubusercontent.com/20840532/32147485-5db3b6cc-bce8-11e7-9c7c-cf7e4fe4388b.jpg)

![app-move here-and-url](https://user-images.githubusercontent.com/20840532/32147487-635fa658-bce8-11e7-84ab-f8b595e74f87.jpg)

**Comment by algorys** [comment]
For first screen, not sure item icons will be better. Or maybe with something showing it's a configuration.

For second screen, I think:

- [x] links to webui is a good idea.

- [x] Move button also.

**Comment by algorys** [comment]
@spea1 not sure I can do something interesting with services icons for webui links ?

**Comment by spea1** [comment]
if it is a lot of work then not

**Comment by algorys** [comment]
@spea1 not a lot of work, but what kind of link I do ? Because I don't know if I can display a view with filtering host & services states ?

@mohierf ?

**Comment by algorys** [comment]
I close this issue because not sure there is something more to do here.
