### ISSUE TITLE
Other color for scrollbar

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#220]
![app-other color for scrollbar](https://user-images.githubusercontent.com/20840532/32147928-6440692a-bcef-11e7-9523-bdb4edbb2767.jpg)

**Comment by algorys** [comment]
@spea1 yes I thought about it. But I do not know what color would be appropriate?

**Comment by mohierf** [comment]
light-grey ?

**Comment by algorys** [comment]
Ok, here is a preview of dark grey (going on blue):

![dark_grey_scroll](https://user-images.githubusercontent.com/8926922/32299590-709a5398-bf56-11e7-90d8-0c49046babc1.png)

And a lightgrey:

![light_grey](https://user-images.githubusercontent.com/8926922/32299624-87863644-bf56-11e7-8bae-d61e016718a0.png)

What is your opinion ?

**Comment by mohierf** [comment]
Dark grey looks better, no ?

**Comment by algorys** [comment]
Done for dark.
