### ISSUE TITLE
Manage not monitored hosts in App

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#228]
See https://github.com/Alignak-monitoring-contrib/alignak-backend/pull/458 to see how App will manage host unmonitored.

If `active_checks_enabled=False` and `passive_checks_enabled=False`, host is not monitored and we don't care of its state.

**Comment by mohierf** [comment]
I managed this in a recent PR on the WebUI ... you must only check if the livesynthesis contains some not_monitored counters to remain compatible with some older backend

See https://github.com/Alignak-monitoring-contrib/alignak-webui/pull/360

**Comment by algorys** [comment]
Done.
