### ISSUE TITLE
Strange icons on login screen

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#229]
Have a look at the icons in the top bar of the login screen:
![image](https://user-images.githubusercontent.com/2932687/35910843-3fdac712-0bf8-11e8-9b59-88cfceac3118.png)

**Comment by algorys** [comment]
Maybe it's due to #230, if you have change working directory ?

**Comment by mohierf** [comment]
Probably ...

**Comment by algorys** [comment]
I reproduced the problem and it seems well linked to the #230.
