### ISSUE TITLE
Try periodically to restablish connection to backend

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#23]
Application stop if connection failed.

She should be able to : 
- [x] Run even the connection to backend failed. 
- [x] Retry connection if backend restart.

To prevent user, maybe app trigger a notification or display an temporary appindicator (see #22)

**Comment by mohierf** [comment]
> To prevent user, see ...

What for? To inform the user I suppose?

**Comment by algorys** [comment]
@mohierf yes. I've update issue to be more explicit.

**Comment by algorys** [comment]
Application continue to run, even if backend is not available. Connection is made at each interval set in `settings.cfg` file.
