### ISSUE TITLE
Alignak-app stops when getting an host

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#231]
![image](https://user-images.githubusercontent.com/2932687/35915833-b49b9526-0c08-11e8-95aa-1098dadb0ab3.png)

**Comment by algorys** [comment]
Ok, strange because it seems host `ek3022fdj-00027` is in database... 

Do you fix icons problem before ? (by pasting images;ini in your workind directory like I said in #230)

Because maybe it's due that app can't found icon to display it :confused:

**Comment by mohierf** [comment]
Yes. Icon problem got fixed on the login screen

**Comment by algorys** [comment]
Ok, after some tests, I've found problem. I use `_overall_state_id` to display some message or icons in Alignak-app. 

But before that value went from 0 to 4. There it seems that in your backend, values range from 0 to 5 ...

I found some tests in Backend and Webui (like here [/test/test_helper.py#L573-L582](https://github.com/Alignak-monitoring-contrib/alignak-webui/blob/d226158e92e8329baaeadc8e03fd4a20588892fd/test/test_helper.py#L573-L582).) but nothing with an `_overall_state_id` equal to 5...

So is it normal to get `_overall_state_id` at 5 or not ?

**Comment by mohierf** [comment]
@algorys : from 0 to 5 it is normal ... 5 is indicating that the host or service is not monitored (passive_checks_enabled is False and active_checks_enabled is False) It is a recent value that I introduced some weeks ago ...

**Comment by mohierf** [comment]
Some doc exist in the Alignak backend doc but I will add some more information about this 😉

**Comment by algorys** [comment]
Fixed.
