### ISSUE TITLE
Make a Windows version

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#24]
It may be interesting to have a Windows version of this app indicator ... many users use this OK :wink:

**Comment by algorys** [comment]
Yes that's true. I will see how to implement that.

**Comment by algorys** [comment]
After some research, it appears that Qt5 (or Qt4) is the best solution.

The alternative is to use win32api, but it will take to double the code (For Windows and for Linux).

Qt provides a portable code and let install the application on other system than Debian (including Windows and Android ...). 

This, however, ask a complete overhaul of the application.

**Comment by algorys** [comment]
@mohierf application can be run under Windows now. The documentation has been updated to explain how to install Alignak-app on Windows.

I'll see how to make an installer more "Windows like" now. (see #37)

**Comment by mohierf** [comment]
:+1:
