### ISSUE TITLE
Allow to set/unset active / passive checks

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#241]
On the host synthesis view, add some toggle controls that will allow to set/unset the `active_checks_enabled` and `passive_checks_enabled` attributes of an host. This will allow to configure the way Alignak will monitor the host

Especially, unsetting the two attributes will make Alignak ignore the host hat will be set as not monitored, like in the WebUI where it appears as greyed.

**Comment by algorys** [comment]
Done :wink:
