### ISSUE TITLE
Proxy management

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#274]
In case a user uses a proxy, there is no way in App to manage it.

According to the documentation of the requests library, a simple definition of the environment variables could be enough to make the client understand that there is a proxy. (See [Requests: proxies](http://docs.python-requests.org/en/latest/user/advanced/#proxies))

So, App could:

- Add a setting in configuration file: `proxy=`
- Define the variable `HTTP_PROXY` or `HTTPS_PROXY` depends if proxy had **https** or not.
- Then login to client.

A rapid test (under Linux):

```python
# Just before login to backend client
import os
os.environ['HTTP_PROXY'] = 'http://10.0.0.1'

# Log output
[2018-03-15,17:05:52]-urllib3.connectionpool: [WARNING] Retrying (Retry(total=4, connect=5, read=5, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError("<urllib3.connection.HTTPConnection object at 0x7f5164b37128>: Failed to establish a new connection: [Errno 110] Connexion terminée par expiration du délai d'attente",))': http://demo.alignak.net:6000/login
```

Because proxy is not here.

**Comment by mohierf** [comment]
Some remarks:
 - not sure that the environment variables will be used on Windows ... to be confirmed.
 - what about a proxy with authentication? Perharps it may be interesting to add some login information in the app configuration file and make them editable on the backend URL configuration window ?

**Comment by algorys** [comment]
This answer on SO is very well explain: [proxies-with-python-requests-module](https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module?answertab=active#tab-top)

**Comment by mohierf** [comment]
Defining a `HTTP_PROXY` environment variable (Linux or Windows) seems to make the Alignak App use a proxy server to connect the backend 😉

**Comment by mohierf** [comment]
User authentication is a must-have !

**Comment by algorys** [comment]
@mohierf yes. I think we need to integrate it in client.

See https://github.com/Alignak-monitoring-contrib/alignak-backend-client/pull/72

**Comment by algorys** [comment]
Done.
