### ISSUE TITLE
Improve App start for BIG backend

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#280]
Improve App start for BIG backends:

- When we have a backend with a thousand services, App takes about one to two minutes to start. 

This is because there are many services to recover.

- On the other hand a request on a host just for its services could accelerate the start and thus avoid having a waiting time too long. 

A test with a host and 50 services seems no slow down App. 

The default is that the problems displayed by the application will have to be updated by the user (or application) as the services are added...

@mohierf , @ddurieux any suggestion for this ?

**Comment by mohierf** [comment]
@algorys : for the problems, you may use a specific request to get all the hosts/services which are problems ? Like the Web UI does ...

**Comment by algorys** [comment]
@mohierf yes, it's a good idea. And store them in a new item. I'll give a try.

**EDIT:**

After some tests, dedicated request for problems and host services are fast enough.

**Comment by algorys** [comment]
With last modifications, start of App is improved:

Before:

```bash
[2018-03-21,17:56:58]-alignak_app.app: [INFO] ----- Alignak-App START -----
[...]
[2018-03-21,17:59:28]-alignak_app.qobjects.app_main: [INFO] Display Alignak-App...
```
App start in **2 minutes 30**  on a big backend... (sometimes a little less)

Now:

```bash
[2018-03-21,17:53:47]-alignak_app.app: [INFO] ----- Alignak-App START -----
[...]
[2018-03-21,17:54:13]-alignak_app.qobjects.app_main: [INFO] Display Alignak-App...
```
Start in **26 seconds** on a big backend !

**Comment by algorys** [comment]
I think this is good.
