### ISSUE TITLE
Limit host history events to 25

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#285]
App should limit the number of host history events to 25. Actually, it seems she take the limit defined in backend pagination by default.

**Comment by mohierf** [comment]
Indeed, whatever the client will request, it will not get more than the maximum pagination defined in the backend configuration... beware of this. You will not get more than the maximum. And, if not specified, you will get the default pagination

**Comment by algorys** [comment]
@mohierf ok. If I do a `get_all()` in backend, does maximum pagination is used ?

**Comment by algorys** [comment]
Done.
