### ISSUE TITLE
Make App tabs movable

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#288]
User can choose to start with problems or host synthesis as default view in settings.

Now App should let user to move tab to its preferred position during run.

**Comment by algorys** [comment]
Now that the tabs can be moved, maybe the setting for the startup display could be reviewed.

Instead of having only choose if problems or synthesis is default view, user could choose the order he prefers according to a simple list:

```ini
tab_order = problems,spy,synthesis`
# or (for p=problems, s=spy, h=synthesis)
tab_order = p,s,h
# or
tab_order = 0,2,1
```

With default value if user set a wrong order.

**Comment by mohierf** [comment]
`p,s,h` looks a good option

**Comment by algorys** [comment]
@mohierf done. I think it's a good feature. After some tests, my prefer order is:

`s,h,p`

Default order will be `h,p,s`. I would change the default value if needed.
