### ISSUE TITLE
Raise an alert when daemons are freshness expired

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#300]
It may be interesting to raise an alert when the Alignak daemons did not got refreshed since a while. If a daemon status is not refreshed since X minutes ... may be the Alignak arbiter is dead !

**Comment by algorys** [comment]
Great idea. 

What time period? One hour ?

**Comment by mohierf** [comment]
I think that 5 / 15 minutes (or a configurable value) may be a good choice 😉

**Comment by algorys** [comment]
I did tests and I think 10 minutes by default is fine. App displays a freshness sometimes from 5 to 6 minutes before recheck.

And allow to configure it behind.

**Comment by algorys** [comment]
@mohierf I've also add message if daemon is not **alive** and change icon if freshness expired :wink:
