### ISSUE TITLE
Several aesthetics and design issues

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#302]
Several aesthetics and design issues.
-----

*@bouchenh, @perretn: please feel free to add your comments and remarks in this issue...*

Host synthesis view: 

- [x]  when hovering the last check **When**, display the real date/time of the check
- [x] the host part of the view height may be reduced to increase the services part ?
- [x] rename "Services of host_name: XX services" to "Services: XX"
- [x] when selecting a service state icon, only the concerned services should be displayed. Perharps, disable the tree view ?

Problems view:

 - [x] Automatic refresh for problems tab 

Spied hosts view:

- [x] do not display "Not monitored" services as problems (**bug**)
- [x] when hovering a problem, display information about the check (date and output)

**Comment by algorys** [comment]
@mohierf all issues have been managed :wink:
