### ISSUE TITLE
Host / Service notification options

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#306]
1. A remark about the popup layout for the hosts notifications. Display options in this order and use this font case:
 - None
 - Alerts:
   - Down
   - Unreachable
   - Recovery
 - Downtime
 - Flapping

1. A remark about the popup layout for the services notifications. Display options in this order and use this font case:
 - None
 - Alerts:
   - Warning
   - Critical
   - Unknown
   - Unreachable
   - Recovery
 - Downtime
 - Flapping

**Note:** the idea behind these remarkes is to propose an easir and ordered layout of the different options 😉 

**Also note** that currently the *Unreachable* option for the services is not proposed...

**Comment by algorys** [comment]
I've change font case and order of options.

But was the word "Alerts" to separate the options part of your request ? Or is it just for the example?

**Comment by mohierf** [comment]
I think it may be interesting to have this word on the interface ... having an UI looking like this:
![image](https://user-images.githubusercontent.com/2932687/39292114-773e12f2-4935-11e8-9614-02c7c589ac1d.png)

with the checks will help the end-user understanding, no?

**Comment by algorys** [comment]
Done.
