### ISSUE TITLE
Remove port in config

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-app#311]
In the config interface, if we remove the port, in the settings is keep the _:_ perhaps delete it to have the url without the _:_ at the end ;)

**Comment by mohierf** [comment]
If port is empty, use 80 for http:// and 443 for https://

**Comment by algorys** [comment]
@mohierf I think @ddurieux  was talking about the case where the backend is reachable with the url (without the port).

So to add the port 80 or 443 would not be really manageable or not wanted.

**Comment by algorys** [comment]
Done. Reopen if needed :wink:

**Comment by mohierf** [comment]
If you are using something like http://127.0.0.1 it is the same as http://127.0.0.1:80. So if port is left empty in the input field, consider it is 80 and not an empty value 😉
