### ISSUE TITLE
Host synthesis tab should include host name

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#312]
Some synthesis view enhancements:
- [x] when an host is displayed in the synthesis view, the tab title should be **Host host_name**
- [ ] a double click on an item in the problems view should drop the host in the synthesis view

**Comment by algorys** [comment]
@mohierf do you think that when the user double clicks on an item, it must also display the synthesis view ? Or just drop the host in the synthesis view

**Comment by mohierf** [comment]
Yes, it would be nice 😃

**Comment by algorys** [comment]
Done.
