### ISSUE TITLE
Question about proxy

### ISSUE THREAD

**Issue by fristotc** [Alignak-monitoring-contrib/alignak-app#317]
Can you confirm that proxy feature (in 1.4.1) has been merge on master branch? Thanks

**Comment by algorys** [comment]
Yes it has been merged in master and develop and therefore in the releases. You should find a menu in the login window to configure it.

**Comment by mohierf** [comment]
I tested this feature with 1.4.1 and with the most recent version 1.4.4

**Comment by fristotc** [comment]
thanks a lot.
