### ISSUE TITLE
Check other Linux distribution, Windows, IOS

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#33]
Alignak-App try to run  on a number of platforms, if it's possible :

1. **Linux**
- [x] Debian-like (Debian, Mint, Ubuntu)
- [ ] FreeBSD
- [ ] Fedora
- [x] RedHat

2. **Windows**
- [x] Windows Server (see #24) (on Server 2012)
- [x] Windows 7, 8, 10
- [x] Windows

3. **Mac**
- [ ] MacOS

This issue is open for **volunteers**. Give me your feedbacks.

Thanks :angel:

**Comment by mohierf** [comment]
Windows 7 and 8: Ok

An installer for this platform is a must-have :wink:

**Comment by algorys** [comment]
Thanks.

@mohierf yes, I'll work on this soon (see #37)

**Comment by algorys** [comment]
I close this issue. The only platform I miss now is OSX. See later and reopen if someone want to install App on this platform.
