### ISSUE TITLE
Check if alignak running

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-app#48]
check if the more recent check is less than xx minutes (for example 30 minutes) to be sure Alignak runs

**Comment by mohierf** [comment]
The Alignak Web service module provides this information ... if the Web Service answers and all the not spare satellites are alive, then Alignak is running :wink:  You can even check, for each satellite the last check timestamp ...

**Comment by ddurieux** [comment]
In my installation, I have only access to the webui, not access to alignak :p

**Comment by algorys** [comment]
So maybe it's the same as #38, no ?

In future version I want to make a detailed window :smiley: 

See #39 also if you have other ideas.

**Comment by mohierf** [comment]
I think the #38 is enough to know if Alignak is running.

Getting the last time check is not a reliable information to know if Alignak is running; as an example, you only have some passive checks and during a period of time (eg. 5 minutes), you do not receive any checks ... you will say Alignak is Down !

**Comment by ddurieux** [comment]
You're right..... and wrong, if you don't have access to alignak, it can't work :p

**Comment by mohierf** [comment]
Ok, so:
1. you give an access to your Alignak, else you do not have any means to know if it is ok
2. you ask the information to the Webui (daemons state page or widget)
3. we extend the alignak backend module to store alignak state information into the backend (see https://github.com/Alignak-monitoring-contrib/alignak-backend/issues/173)

**Comment by algorys** [comment]
Ok, #38 is now implemented.

Do you thinks it's enough or https://github.com/Alignak-monitoring-contrib/alignak-backend/issues/173 is required also to see if Alignak is running ?

**Comment by mohierf** [comment]
I think that the best would be to implement also an access to the backend. As such, if some configuration only open an access to the Alignak backend, you will also have the information ... but it does not seem to be a priority ...

**Comment by algorys** [comment]
Ok @mohierf and @ddurieux .

Is there a way now to access to daemon states with `backend-client` ?

**Comment by mohierf** [comment]
The most recent develop branch of the alignak backend includes an endpoint to get the alignak daemons states: https://github.com/Alignak-monitoring-contrib/alignak-backend/blob/develop/alignak_backend/models/alignakdaemon.py

The alignak backend module will feed this endpoint but it is not yet available: @ddurieux do you confirm?

**Comment by algorys** [comment]
Wainting for https://github.com/Alignak-monitoring-contrib/alignak-module-backend/issues/53 to get it fully functionnal.

**Comment by algorys** [comment]
This feature is fully implemented :metal:
