### ISSUE TITLE
Implement acknowledged and downtime states

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#54]
Application does not manage `acknowledged` and `downtime`. If user use WebUI also, there is a risk of confusion.

Alignak-App will also be clearer if it displays all the states.

- [x] Implement  `acknowledged` state
- [x] Implement `downtime` state

**Comment by algorys** [comment]
With the #61, it's not sure that feature is usefull. 

Change to `idea` label and see in future whether it is requested or not.

**Comment by mohierf** [comment]
With the current version, you get information from the backend livesynthesis, right? So, if a host/service is not ok, it means that it has not been acknowledged ... so currently is enough for me

**Comment by spea1** [comment]
acknowledged and downtime states only view "count" in the app not manage, these are useful information

**Comment by algorys** [comment]
Ack and downtime are now fully implemented in application :smiley:
