### ISSUE TITLE
Backend connection parameters

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#57]
You should add a `token` parameter in the `[backend]` section of the configuration file. The *token* is provided by the backend when you use the */login* and it may included in the configuration file instead of the username / password. It is a more secure solution ...

**Comment by algorys** [comment]
086d947 : Connection can now be done with token, by setting it in "username" option and leave "password" empty.

@mohierf Do you think I have to remove connection with "username" and "password" and just let "token" possibility ?

**Comment by mohierf** [comment]
No, is is enough as you did :wink:
