### ISSUE TITLE
Trigger notifications inside Alignak-app

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#58]
Actually, Alignak-app (App) trigger notification on desktop by simply check states of hosts and services.

One feature that could be pretty good would be that alignak store somewhere in backend a notification and App check regularly in backend what is already send or not to the user...

Here is a small example of what this could give:

1. Alignak send a notification.
2. This is stored in backend
3. App checks every "x" seconds in the backend (with client) the notifications that have be send.
3. App retrieves notifications that have not yet been displayed / acknowledged by the user and display it.

The advantage of such a system is that  provides one more way to warn the user.

Even if you no longer have a mail server but still access to Alignak, the user can continue to receive notifications.

**Comment by mohierf** [comment]
For this feature I imagine two possible solutions:

1. Currently the Alignak monitoring logs are built by a broker module using a Python logger. Perharps there is a solution with the Python logger to get notified in the App ?

2. As proposed here: https://github.com/Alignak-monitoring-contrib/alignak-backend/issues/176, the monitoring logs (including notifications, acknowledges, ...) may be stored in the alignak backend and, as such, made available to a third-party application. The App may fetch information in the backend ...

I think that the second solution is quite easy to implement ...

**Comment by mohierf** [comment]
This PR (https://github.com/Alignak-monitoring-contrib/alignak-backend/pull/179) for the Alignak backend will allow to get information in the history data model (some information still exit in this model and it will be extended for new events such as notifications).

The backend history model will be fed thanks to the Alignak logs module: https://github.com/Alignak-monitoring-contrib/alignak-module-log

**Comment by algorys** [comment]
I do not know if this feature can still be interesting? 

Notifications should remain for alignak modules. App already sends enough notifications to warn the user ?

And I think with implementation of #114 she will be complete :wink: 

@mohierf @ddurieux your advice ?

**Comment by mohierf** [comment]
IMHO, sure it is interesting ... have a look to the backend `history` endpoint. The App should notify an information popup for the events that are stored in this endpoint ?

**Comment by mohierf** [comment]
Have a look to the history data model of the backend to have an idea of all the event types that may exist in the history of an host/service: https://github.com/Alignak-monitoring-contrib/alignak-backend/blob/develop/alignak_backend/models/history.py

**Comment by algorys** [comment]
Done :tada:
