### ISSUE TITLE
Display an host synthesis view

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#61]
A very interesting (IMHO) new feature for the app :wink: 

**Use case** in a call center, John gets a phone call from his customer: 
 - C: "My device is broken !"
 - J: "Which device? What's your device name?"
 - C: "myHost!"

John activates its alignak-app and enter "myh" in the search field. Then the app proposes a list of matching hostnames from which John chooses **myHost**.

The alignak-app diplays a popup centered on the screen with the main **myHost** elements:
 - host name, host address
 - information about the last check: date, state and output
 - information about the last sent notifications
 - for each service, information about the last check: date, state and output

With this information, John can have an idea about the problem existing on his customer's device and help him to fix the problem. Perharps he may even run the host or service event handler thanks to a button click and fix the problem remotely :wink: 

- [x] add an `acknowledge` button (if host overall state is not ok)
    *This is allowed with acknowledge endpoint in the alignak backend*

- [x] add a `schedule a downtime` button (if host overall state is not ok)
    *This is allowed with downtime endpoint in the alignak backend*

- [x] update the host overall state (including services states)
  
- [ ] add a `launch event handler` button (if an host event handler exists)
    *This will require a modification in the alignak backend*
- [x] Add checks to see if `ack` or `downtime` is done for host and propose only if overall state is not ok.

**Comment by mohierf** [comment]
No comments on this issue :wink: 

IMHO it is a killer feature! @algorys will you be able to make a draft version soon for this?

**Comment by algorys** [comment]
@mohierf I've :+1:

Yes I'll try to make a draft for this ASAP :hammer: I thiink I'll make that for `0.5` version  :wink:

**Comment by algorys** [comment]
- [x] Fix time for last_check with UTC timestamp to convert to the current user timezone

**Comment by mohierf** [comment]
Perharps some few modifications on the current view:
![image](https://cloud.githubusercontent.com/assets/2932687/20885876/7400c976-baf3-11e6-86e6-67b171883a79.png)

(@mohierf I move list at issue head)

**Comment by mohierf** [comment]
Host overall state is computed as is:
```
        Get the element real worst state, including:
        - the acknowledged state
        - the downtime state

        The worst state is (prioritized):
        - an host down (4)
        - an host unreachable (3)
        - an host downtimed (2)
        - an host acknowledged (1)
        - an host up (0)
```

If the host overall state is > 2 then services states are ignored. Else the host overall state is the maximum value of the host overall state and each service overall state.

Service overall state is computed as is: 
```
        Get the element real worst state, including:
        - the acknowledged state
        - the downtime state

        The worst state is (prioritized):
        - a service critical or unreachable (4)
        - a service warning or unknown (3)
        - a service downtimed (2)
        - a service acknowledged (1)
        - a service ok (0)

        *Note* that services in unknown state are considered as warning, and  unreachable ones
        are considered as critical!
```

----

Note that this solution can also take place to compute an hosts group overall state or even the whole system overall state :wink:

**Comment by algorys** [comment]
Now ack and downtime buttons are implemented.

**Comment by algorys** [comment]
This feature is implemented (ouf !! :smile: ).

> add a launch event handler button (if an host event handler exists)
> This will require a modification in the alignak backend

is moved to #91.
