### ISSUE TITLE
Alignak states raise an unhandled exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#64]
On Windows, with the current develop branch, the *Alignak States* menu raises an `Unhandled Python exception`

**Comment by algorys** [comment]
7a3ca3a try to catch more problems.

Actually, can't reproduce the bug.

@mohierf , as you said : 

Result of `pip freeeze`:

```
alignak-app==0.5.0 
alignak-backend-client==0.5.2 
configparser==3.5.0 
future==0.16.0 
PyQt5==5.7 
requests==2.12.1 
sip==4.18.1 
```

Windows version : 7

**Comment by mohierf** [comment]
Not observed anymore, I close
