### ISSUE TITLE
Missing gi in requirements.txt

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#7]
Python gi package seems necessary but it is not included in the requirements.txt file

**Comment by mohierf** [comment]
Indeed, `gi` must not be installed with pip ... but with the distro's packages.

```
sudo apt-get install python-gi
```

The doc should be updated for this

**Comment by algorys** [comment]
I've update docs and link in README in fix 87026fa3d2652430d0651cdb28ad94b2f23839e0
