### ISSUE TITLE
Alignak app user login for the backend

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#74]
Currently, the application connects to the alignak backend with the credentials stored in the configuration file. It may be interesting, when no credentials are defined in the configuration file, to propose a login form for the user.

As such, the app will connect to the alignak backend with the credentials (username / password) of the form ans thus will access only to its allowed data.

-----

**Note** that the backend is managing user's credentials for the backend data ...

**Comment by algorys** [comment]
Implemented @mohierf 

When no credentials are defined in the configuration file, a login window is shown :smiley:

**Comment by algorys** [comment]
Seems actually bugged...

**Comment by algorys** [comment]
Fixed.
