### ISSUE TITLE
Missing service Unreachables

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#75]
**Service status and count is missing for:**	
- Services "Acknowledged"
- Services "Unreachable" count with "UNKNOWN"
- Services "In scheduled downtime"

**Comment by algorys** [comment]
For services  "Acknowledged" and "Unreachable", please refer to #54 :smiley: 

- [x] Services Unreachables

**Comment by algorys** [comment]
Implemented.
