### ISSUE TITLE
Launching from shell should alert 

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#8]
In an SSH connection, when launched from shell, `alignak_app` makes a segmentation fault:

```
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(alignak_app:14533): Gtk-CRITICAL **: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
/usr/lib/python2.7/dist-packages/gi/overrides/__init__.py:326: Warning: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
  return super_init_func(self, **new_kwargs)
Segmentation fault (core dumped)
```

Perharps this should be catched and a message inform the user to launch from a desktop ...

**Comment by algorys** [comment]
Ok,

Have you tried with following command ?

`export DISPLAY=:1`

Like say here [Can't launch graphical apps from terminal after updating to 15.10](http://askubuntu.com/questions/768508/cant-launch-graphical-apps-from-terminal-after-updating-to-15-10).

It seems same issue appears on 16.04.

**Comment by mohierf** [comment]
No, I did not tried. The idea behind this issue is simply to avoid displaying error message ... if you cannot test if we are in GTK or catch the errors, no matter ...

**Comment by algorys** [comment]
Idea is great. I'll look at that.

**Comment by algorys** [comment]
That's catch
