### ISSUE TITLE
Rename Synthesis view to Host synthesis view

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#82]
The Host synthesis view panel title should be: "Host synthesys view", no ?

**Comment by algorys** [comment]
I was thinking display other informations like the number of hosts and services... so I don't know in fact :wink:

**Comment by mohierf** [comment]
IMHO, this panel must remain very simple because of the audience it is intended to ... a call center people do not need too much information.

**Comment by algorys** [comment]
You're right, I'll indicate hosts and services counts by an other way. So rename is ok !

**Comment by algorys** [comment]
Implemented.
