### ISSUE TITLE
No more need for a Webui link

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#83]
Is there still any need for a WebUI link in the app ?

Live synthesis, Hosts/services count, Host synthesis, Alignak states are available in the backend. What is fecthed from the WebUI ?

**Comment by algorys** [comment]
There is nothing fetched from WebUI, you are right. 

WebUI link are not needed anymore :+1:

**Comment by spea1** [comment]
**Is that a joke, if not:** 
- I find the link to webui with filter good
- I am even for, link in notification window
![app004](https://cloud.githubusercontent.com/assets/20840532/20906283/901de82e-bb47-11e6-94da-b7fb01bf6386.jpg)

**Comment by spea1** [comment]
Even more Webui link 👍 
![app011](https://cloud.githubusercontent.com/assets/20840532/21115535/114e33f8-c0b2-11e6-8177-fbe12b179125.jpg)

**Comment by algorys** [comment]
Currently, link to webui still here in menu. The rest is transferred to #115.
