### ISSUE TITLE
Menu items 

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#87]
- [x] In the menu, replace:
 - "Alignak states" with "Alignak status"
 - "Synthesis view" with "Host view"

- [x] Hosts / Services icon color should have the color of the worst state (green if all is ok, orange if some warnings, ...)
    Indeed, using the same computation as for the host overall state, you can define the hosts overall state

I think this should be more clear for the user :wink:

**Comment by algorys** [comment]
Very good idea and implemented :)
