### ISSUE TITLE
What decides on the level of notification

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#89]
Currently, Alignak-app deicdes his level of notification like the following:

* if services critical > 0 or hosts down > 0 then level notif is `critical`.
* if services unknown > 0 or services warning > 0 or hosts unreachable > 0 then level notif is `warning`.
* else level notif is `ok`

Maybe it should be something like that:

* if states changes are "ok" -> 2 host becomes UP from DOWN, level notif is `ok`
* if states changes are "warn" -> 4 services becomes WARNING from UP, level notif is `warning`
* if states changes are "critical" -> 1 host becomes DOWN, 4 services becomes CRITICAL, level notif is `critical`

@ddurieux, @mohierf what do you think of that ?

**Comment by mohierf** [comment]
IMHO, I will set two notifications information:
 - the overall system state
 - the current change

The overall system state should be computed as explained here: https://github.com/Alignak-monitoring-contrib/alignak-app/issues/61#issuecomment-265759034 and the notification popup background may be coloured according to the state.

 The current change as you stated will be used to colour the background of the current notification banner.

**Comment by algorys** [comment]
This feature will be implemented with #113 and ticks.
