### ISSUE TITLE
Release a French version

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#93]
Make the alignak application localizable ...

**Comment by algorys** [comment]
I've been thinking about it for a while 😄 but it needs lot of changes.

**Comment by mohierf** [comment]
If you are using a lib like gettext, it is not that hard to localize the text strings ... I did it for the WebUI qui easily.

**Comment by algorys** [comment]
After many try, getttext finnaly work.

For big application, this trick https://stackoverflow.com/questions/739314/easiest-way-to-generate-localization-files is very usefull ( @mohierf  I think this can be useful for the WebUI too).

We have only to define files in a file and `xgettext` will parse them to create the `.pot`.

For alignak-app, I'll create `POTFILES.in` to list all files who need translating. Then go in locales folder and run:

```bash
xgettext --files-from=POTFILES.in --directory=. --output=messages.pot
```

After, we have just to create the corresponding `.po` and `.mo` for each language.

**Comment by algorys** [comment]
First French version is now done.

**Comment by algorys** [comment]
Missing translation in:

`user_profile.py`
`service_widget_item.py`

**Comment by algorys** [comment]
Done.
