### ISSUE TITLE
Propose server url in login form

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#94]
Perhaps, App can suggest to the user, during the connection form, to define the server's url (backend).

This way, it will simplify the life of the Windows users and also that of the sysadmin.

The first time the application starts, it sets the current configuration value. If it has been changed, it will update the configuration file.

**Comment by mohierf** [comment]
Note that you can define some variables in the configuration file and that you should have a variable set as `alignak_url` and that you will use for the other variables.
```
alignak_url=http://127.0.0.1
alignak_backend=%(alignak_url)s:5001
alignak_ws=%(alignak_url)s:8888
```

`alignak_url` may be updated if the user changes the URL in the login form and then it will update all the related URLs

----
See python ConfigParser in interpolation mode: https://docs.python.org/2/library/configparser.html

**Comment by algorys** [comment]
Implemented.
