### ISSUE TITLE
The app does not start after setup (Setup Alignak-app 0.5.exe)

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#95]
startup error:

- Windows Server 2012 R2 missing VCRUNTIME140.dll
- Windows Server 2008 + Windows 7

![win7-srv2008](https://cloud.githubusercontent.com/assets/20840532/21161322/5e4d6b3e-c188-11e6-8000-e4f3584a0411.jpg)

**Comment by algorys** [comment]
Normally 415fff7 fiox the problems and install redistribuables.
