### ISSUE TITLE
The app does not start with windows 32 bits (Setup Alignak-app 0.5.exe)

### ISSUE THREAD

**Issue by aymef** [Alignak-monitoring-contrib/alignak-app#97]
Startup error :
- Windows 7 32 bits

![alignakerr](https://cloud.githubusercontent.com/assets/6781316/21174768/5a305960-c1df-11e6-881b-8ff4954aef19.JPG)

**Comment by algorys** [comment]
Thanks for feedback. I'll try to release a 32bits version.

**Comment by algorys** [comment]
Report to #184
