### ISSUE TITLE
Alignak status notification

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#98]
When an Alignak deamon is detected as not alive by the app it should raise a specific alerting popup.

Alignak overall state should be defined as:
 - OK, if all daemons are alive
 - WARNING, if some daemons are not alive (whether they are spare or not)
 - CRITICAL, is some daemons are not alive since a long time (more than 5 minutes?)

This popup should be the same as the Alignak status popup with a greeen/orange/red background (?)

**Comment by algorys** [comment]
With the implementation of ticks in app, this kind of things can be send to user.  (See last Windows setup or install from develop to see what ticks are looked. See also #108 )

Ex: "ALERT: Scheduler-master is down since 10 min !"

User can then go to Alignak Status to have a resume.

**Comment by mohierf** [comment]
Ticks is a great feature !

**Comment by algorys** [comment]
This is not fully implemented, so I reopen issue.

Leave:

* Periodic checks to see if daemons still alive
* Maybe set a timer to see how long there is a problem

**Comment by algorys** [comment]
Implemented :gift: 

App now make periodic checks on alignak status. Check are done each minutes (maybe 5 minutes ?). Here is how I implement that:

If all is ok, nothing is done. Status are already display at start  :yum:

If some daemons are down, App display a WARN banner. 

If all daemons are down, App display an ALERT banner.

If alignak_daemons back to normal, OK banner is send

Then if user wants to know more, Alignak Status in system tray display all informations for each daemons.

I think this is a good implementation of the idea ?

**Comment by mohierf** [comment]
:+1:  for me. I think that all the dameons DOWN is something that will never happen

Perharps that you should ALERT if an arbiter is down, because without any arbiter, Alignak will really be unstable because no daemon will be able to restart the other daemons

**Comment by algorys** [comment]
Ok I'll change to arbiter.

**Comment by algorys** [comment]
ALERT banner for Arbiter DOWN is implemented. I like this feature.

Wainting for #48 to have something better.
