### ISSUE TITLE
Miss message lost connection and auto change to reconnect mode

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#99]
APP connection is lost, auto change from notification mode to reconnect mode 
(eg 60 x check_interval = 1h)  new pop connection is lost "Try to reconnect 34 of 60".

**Comment by algorys** [comment]
Yes good idea. I can prevent user by #108 .

**Comment by algorys** [comment]
Now App has a reconnect mode :wink:
